/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NavigatorRouteImport } from './routes/navigator'
import { Route as MapRouteImport } from './routes/map'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CapitalRouteImport } from './routes/capital'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapIndexRouteImport } from './routes/map.index'
import { Route as SettingsThemeRouteImport } from './routes/settings.theme'
import { Route as MapAddCompanyRouteImport } from './routes/map.add-company'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as NavigatorResourceIdRouteImport } from './routes/navigator.resource.$id'
import { Route as MapCompanyIdRouteImport } from './routes/map.company.$id'
import { Route as MapClaimIdRouteImport } from './routes/map.claim.$id'

const NavigatorRoute = NavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitalRoute = CapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapRoute,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/settings/theme',
  path: '/settings/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const MapAddCompanyRoute = MapAddCompanyRouteImport.update({
  id: '/add-company',
  path: '/add-company',
  getParentRoute: () => MapRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorResourceIdRoute = NavigatorResourceIdRouteImport.update({
  id: '/resource/$id',
  path: '/resource/$id',
  getParentRoute: () => NavigatorRoute,
} as any)
const MapCompanyIdRoute = MapCompanyIdRouteImport.update({
  id: '/company/$id',
  path: '/company/$id',
  getParentRoute: () => MapRoute,
} as any)
const MapClaimIdRoute = MapClaimIdRouteImport.update({
  id: '/claim/$id',
  path: '/claim/$id',
  getParentRoute: () => MapRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/capital': typeof CapitalRoute
  '/dashboard': typeof DashboardRoute
  '/ecosystem': typeof EcosystemRoute
  '/events': typeof EventsRoute
  '/jobs': typeof JobsRoute
  '/map': typeof MapRouteWithChildren
  '/navigator': typeof NavigatorRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/map/add-company': typeof MapAddCompanyRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/map/': typeof MapIndexRoute
  '/map/claim/$id': typeof MapClaimIdRoute
  '/map/company/$id': typeof MapCompanyIdRoute
  '/navigator/resource/$id': typeof NavigatorResourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/capital': typeof CapitalRoute
  '/dashboard': typeof DashboardRoute
  '/ecosystem': typeof EcosystemRoute
  '/events': typeof EventsRoute
  '/jobs': typeof JobsRoute
  '/navigator': typeof NavigatorRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/map/add-company': typeof MapAddCompanyRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/map': typeof MapIndexRoute
  '/map/claim/$id': typeof MapClaimIdRoute
  '/map/company/$id': typeof MapCompanyIdRoute
  '/navigator/resource/$id': typeof NavigatorResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/capital': typeof CapitalRoute
  '/dashboard': typeof DashboardRoute
  '/ecosystem': typeof EcosystemRoute
  '/events': typeof EventsRoute
  '/jobs': typeof JobsRoute
  '/map': typeof MapRouteWithChildren
  '/navigator': typeof NavigatorRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/map/add-company': typeof MapAddCompanyRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/map/': typeof MapIndexRoute
  '/map/claim/$id': typeof MapClaimIdRoute
  '/map/company/$id': typeof MapCompanyIdRoute
  '/navigator/resource/$id': typeof NavigatorResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/capital'
    | '/dashboard'
    | '/ecosystem'
    | '/events'
    | '/jobs'
    | '/map'
    | '/navigator'
    | '/auth/login'
    | '/auth/signup'
    | '/map/add-company'
    | '/settings/theme'
    | '/map/'
    | '/map/claim/$id'
    | '/map/company/$id'
    | '/navigator/resource/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/capital'
    | '/dashboard'
    | '/ecosystem'
    | '/events'
    | '/jobs'
    | '/navigator'
    | '/auth/login'
    | '/auth/signup'
    | '/map/add-company'
    | '/settings/theme'
    | '/map'
    | '/map/claim/$id'
    | '/map/company/$id'
    | '/navigator/resource/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/capital'
    | '/dashboard'
    | '/ecosystem'
    | '/events'
    | '/jobs'
    | '/map'
    | '/navigator'
    | '/auth/login'
    | '/auth/signup'
    | '/map/add-company'
    | '/settings/theme'
    | '/map/'
    | '/map/claim/$id'
    | '/map/company/$id'
    | '/navigator/resource/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CapitalRoute: typeof CapitalRoute
  DashboardRoute: typeof DashboardRoute
  EcosystemRoute: typeof EcosystemRoute
  EventsRoute: typeof EventsRoute
  JobsRoute: typeof JobsRoute
  MapRoute: typeof MapRouteWithChildren
  NavigatorRoute: typeof NavigatorRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/navigator': {
      id: '/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof NavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capital': {
      id: '/capital'
      path: '/capital'
      fullPath: '/capital'
      preLoaderRoute: typeof CapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/'
      fullPath: '/map/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof MapRoute
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/settings/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/add-company': {
      id: '/map/add-company'
      path: '/add-company'
      fullPath: '/map/add-company'
      preLoaderRoute: typeof MapAddCompanyRouteImport
      parentRoute: typeof MapRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator/resource/$id': {
      id: '/navigator/resource/$id'
      path: '/resource/$id'
      fullPath: '/navigator/resource/$id'
      preLoaderRoute: typeof NavigatorResourceIdRouteImport
      parentRoute: typeof NavigatorRoute
    }
    '/map/company/$id': {
      id: '/map/company/$id'
      path: '/company/$id'
      fullPath: '/map/company/$id'
      preLoaderRoute: typeof MapCompanyIdRouteImport
      parentRoute: typeof MapRoute
    }
    '/map/claim/$id': {
      id: '/map/claim/$id'
      path: '/claim/$id'
      fullPath: '/map/claim/$id'
      preLoaderRoute: typeof MapClaimIdRouteImport
      parentRoute: typeof MapRoute
    }
  }
}

interface MapRouteChildren {
  MapAddCompanyRoute: typeof MapAddCompanyRoute
  MapIndexRoute: typeof MapIndexRoute
  MapClaimIdRoute: typeof MapClaimIdRoute
  MapCompanyIdRoute: typeof MapCompanyIdRoute
}

const MapRouteChildren: MapRouteChildren = {
  MapAddCompanyRoute: MapAddCompanyRoute,
  MapIndexRoute: MapIndexRoute,
  MapClaimIdRoute: MapClaimIdRoute,
  MapCompanyIdRoute: MapCompanyIdRoute,
}

const MapRouteWithChildren = MapRoute._addFileChildren(MapRouteChildren)

interface NavigatorRouteChildren {
  NavigatorResourceIdRoute: typeof NavigatorResourceIdRoute
}

const NavigatorRouteChildren: NavigatorRouteChildren = {
  NavigatorResourceIdRoute: NavigatorResourceIdRoute,
}

const NavigatorRouteWithChildren = NavigatorRoute._addFileChildren(
  NavigatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CapitalRoute: CapitalRoute,
  DashboardRoute: DashboardRoute,
  EcosystemRoute: EcosystemRoute,
  EventsRoute: EventsRoute,
  JobsRoute: JobsRoute,
  MapRoute: MapRouteWithChildren,
  NavigatorRoute: NavigatorRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  SettingsThemeRoute: SettingsThemeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
